# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-22.04"
    (1..4).each do |i|
      config.vm.define "node-#{i}" do |node|
        node.vm.network "private_network", ip: "192.168.33.#{i}0"
        config.vm.provision "shell", inline: <<-SHELL
          echo "hello from node #{i}"
          apt-get update
          apt-get upgrade -y
        SHELL
        
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "2048"
          vb.cpus = "2"
        end
      end
    end
end
